cc_binary(
    name = "v4l2_console",
    srcs = [
        "v4l2-console.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//camera",
    ],
    target_compatible_with = select({
        "//cuda:use_hip": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)
