cc_binary(
    name = "video_viewer",
    srcs = ["video-viewer.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//camera",
        "//network",
        "//video:video_output_create",
        "//video:video_source_create",
    ],
    target_compatible_with = select({
        "//cuda:use_hip": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)
