load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cc_binary(
    name = "gl_display_test",
    srcs = [
        "gl-display-test.cpp",
    ],
    linkopts = [
        "-lGL",
        "-lGLEW",
        "-lGLU",
        "-lX11",
    ],
    visibility = ["//visibility:public"],
    target_compatible_with = select({
        "//cuda:use_hip": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":cuda_lib",
        "//base",
        "//codec",
        "//display",
        "//network",
    ] + select({
        "//cuda:use_hip": [],
        "//conditions:default": [
            "//cuda:cuda_lib",
            "@local_cuda//:cuda_runtime",
        ],
    }),
)

cuda_library(
    name = "cuda_lib",
    srcs = glob(["*.cu"]),
    hdrs = glob(["*.h"]),
    copts = [
        "-Xcompiler=-fPIC",
        "-Xcompiler=-g",
        "-g",
    ],
    visibility = ["//visibility:public"],
    target_compatible_with = select({
        "//cuda:use_hip": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":headers",
    ] + select({
        "//cuda:use_hip": ["//cuda:hip_cuda_lib"],
        "//conditions:default": ["//cuda:cuda_cuda_lib", "@local_cuda//:cuda_runtime"],
    }),
)

cc_library(
    name = "headers",
    hdrs = [
        "cudaInteropKernels.h",
    ],
    visibility = ["//visibility:public"],
    deps = select({
        "//cuda:use_hip": [],
        "//conditions:default": ["@local_cuda//:cuda_runtime"],
    }),
)
