cc_binary(
    name = "v4l2_display",
    srcs = [
        "v4l2-display.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//base",
        "//camera",
        "//display",
    ],
    target_compatible_with = select({
        "//cuda:use_hip": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)
