cc_binary(
    name = "test_cuda_blend",
    srcs = [
        "testCudaBlend.cpp",
    ],
    linkopts = [
        "-ltiff",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//stitch:cuda_pano",
        "//display",
        "@local_cuda//:cuda_runtime",
        "@opencv_linux//:opencv",
    ],
)
