load("@rules_cc//cc:defs.bzl", "cc_library")

HIP_COPTS = select({
    "//cuda:use_hip": [
        "-DJETSON_USE_HIP",
    ],
    "//conditions:default": [],
})

cc_library(
    name = "video_output",
    srcs = [
        "videoOutput.cpp",
    ],
    hdrs = [
        "videoOutput.h",
    ],
    copts = [
        "-Wno-deprecated-declarations",
    ] + HIP_COPTS,
    visibility = ["//visibility:public"],
    deps = [
        ":video_options",
        "//threads",
    ],
)

cc_library(
    name = "video_source",
    srcs = [
        "videoSource.cpp",
    ],
    hdrs = [
        "videoSource.h",
    ],
    includes = ["."],
    copts = HIP_COPTS,
    visibility = ["//visibility:public"],
    deps = [
        ":video_options",
        "//base:base_includes",
        "//camera:camera_includes",
        "//image:image_format",
        "@glib",
    ],
)

cc_library(
    name = "video_source_create",
    srcs = [
        "videoSourceCreate.cpp",
    ],
    hdrs = [
    ],
    includes = ["."],
    copts = HIP_COPTS,
    visibility = ["//visibility:public"],
    deps = [
        ":video_options",
        ":video_source",
        "//base:base_includes",
        "//camera",
        "//codec:gst_decoder",
        "//image",
    ],
)

cc_library(
    name = "video_output_create",
    srcs = [
        "videoOutputCreate.cpp",
    ],
    hdrs = [
    ],
    includes = ["."],
    copts = HIP_COPTS,
    visibility = ["//visibility:public"],
    deps = [
        ":video_options",
        ":video_output",
        "//base:base_includes",
        "//camera",
        "//codec",
        "//display",
        "//image",
    ],
)

cc_library(
    name = "video_options",
    srcs = [
        "videoOptions.cpp",
    ],
    hdrs = [
        "videoOptions.h",
    ],
    copts = [
        "-std=c++17",
        "-Wno-sign-compare",
    ] + HIP_COPTS,
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//base",
        "//image:image_format",
        "//network:network_basic",
    ],
)
