load("@rules_cc//cc:defs.bzl", "cc_library")

INCLUDE_PREFIX = "jetson-utils/display"

cc_library(
    name = "display",
    srcs = [
      "glDisplay.cpp",
      "glTexture.cpp",
      "glWidget.cpp",
    ],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-sign-compare",
        "-Wno-error=switch",
    ],
    linkopts = [
        "-lGL",
        "-lGLU",
        "-lGLEW",
        "-lX11",
    ],
    visibility = ["//visibility:public"],
    deps = [        
        ":display_includes",
        ":gl_buffer",
        ":gl_utility",
        ":gl_events",
        ":gl_camera",
        "//base",
        "//cuda:cuda_lib",
        "//network",
        "//video:video_output",
    ],
)

cc_library(
    name = "display_includes",
    srcs = [],
    hdrs = # glob(["*.h"]), 
    [
      "glBuffer.h",
      "glDisplay.h",
      "glTexture.h",
      "glWidget.h",
    ],
    includes = ["."],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        ":gl_utility",
        "//base:base_includes",
    ],
)

cc_library(
    name = "gl_utility",
    srcs = [
    ],
    hdrs = [
        "glUtility.h",
    ],
    includes = ["."],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
      "//base",
    ],
)

cc_library(
    name = "gl_buffer",
    srcs = [
        "glBuffer.cpp",
    ],
    hdrs = [
        "glBuffer.h",
    ],
    includes = ["."],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
      ":gl_utility",
      "//cuda:cuda_utility",
    ],
)

cc_library(
    name = "gl_events",
    srcs = [
        "glEvents.cpp",
    ],
    hdrs = [
        "glEvents.h",
    ],
    includes = ["."],
    linkopts = [
        "-lGL",
        "-lGLEW",
        "-lX11",
    ],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
      ":display_includes",
      "//video:video_output",
    ],
)

cc_library(
    name = "gl_camera",
    srcs = [
        "glCamera.cpp",
    ],
    hdrs = [
        "glCamera.h",
    ],
    includes = ["."],
    include_prefix = INCLUDE_PREFIX,
    linkopts = [
        "-lGL",
        "-lGLEW",
        "-lX11",
    ],
    visibility = ["//visibility:public"],
    deps = [
      ":gl_events",
      ":display_includes",
      "//video:video_output",
    ],
)
