cc_library(
    name = "threads",
    srcs = glob(["*.cpp"]),
    hdrs = glob([
        "*.h",
        "*.inl",
    ]),
    includes = ["."],
    copts = select({
        "//cuda:use_hip": [
            "-DJETSON_USE_HIP",
            "-DJUT_INCLUDE_HIP_HEADERS",
            "-isystem",
            "external/rocm_sdk_includes/include",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//base:base_includes",
        "//cuda:cuda_mapped_memory",
    ],
)
