cc_binary(
    name = "camera_viewer",
    srcs = [
        "camera-viewer.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//camera",
        "//codec",
        "//display",
    ],
    target_compatible_with = select({
        "//cuda:use_hip": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)
