load("@rules_cc//cc:defs.bzl", "cc_library")

INCLUDE_PREFIX = "jetson-utils/image"

cc_library(
    name = "image",
    srcs = [
        "imageWriter.cpp",
    ],
    copts = [
        "-Wno-error=switch",
        "-Wno-deprecated-declarations",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":image_format",
        ":image_includes",
        ":image_loader",
        "//cuda:cuda_lib_headers",
        "//cuda:colorspace_lib",
        "//threads",
        "//video:video_includes",
    ],
)

cc_library(
    name = "image_loader",
    srcs = [
        "imageIO.cpp",
        "imageLoader.cpp",
    ],
    hdrs = [
        "imageIO.h",
        "imageLoader.h",
    ],
    copts = [
        "-Wno-error=switch",
        "-Wno-deprecated-declarations",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":stb_image",
        "//video:video_source",
    ],
)

cc_library(
    name = "stb_image",
    srcs = [],
    hdrs = [
        "stb/stb_image.h",
        "stb/stb_image_resize.h",
        "stb/stb_image_write.h",
        "stb/stb_truetype.h",
    ],
    includes = ["."],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        "//base:base_includes",
        "//video:video_options",
    ],
)

cc_library(
    name = "image_includes",
    srcs = [],
    hdrs = [
        "imageWriter.h",
        "loadImage.h",
    ],
    includes = ["."],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        "//base:base_includes",
        "//video:video_options",
    ],
)

cc_library(
    name = "image_format",
    srcs = [],
    hdrs = [
        "imageFormat.h",
        "imageFormat.inl",
    ],
    copts=[
        "-Wno-error=switch",
    ],
    includes = ["."],
    include_prefix = INCLUDE_PREFIX,
    visibility = ["//visibility:public"],
    deps = [
        "//base:base_includes",
        "//cuda:cuda_utility",
    ],
)
